version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: test
      POSTGRES_PASSWORD: test
      POSTGRES_USER: test
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: on-failure

  redis:
    image: redis:latest
    restart: on-failure
    volumes:
      - redis-data:/var/lib/redis
    ports:
      - 6379:6379

volumes:
  postgres-data:
  redis-data: